### ISSUE TITLE
Attempted to call method "getPagerType"

### ISSUE THREAD

**Issue by Malstrom** [sonata-project/SonataDoctrineORMAdminBundle#430] opened 2015-02-22 22:50 UTC

**Comment by pulzarraider** [comment] 2015-02-23 00:19
Duplicate of #424.

Please do not mix the stable (~2.3) and unstable versions (dev-master) of SonataAdminBundle, SonataDoctrineORMAdminBundle, SonataCoreBundle. Use stable (tagged) versions of all bundles or use dev-master of SonataAdminBundle, SonataDoctrineORMAdminBundle, SonataCoreBundle if you want to try new features.

**Closed** 2015-02-23 00:20 UTC
