### ISSUE TITLE
JS log error: element is an anchor, skipping action

### ISSUE THREAD

**Issue by lucachaco** [sonata-project/SonataDoctrineORMAdminBundle#395] opened 2014-10-09 09:32 UTC
I have updated the package but know I keep getting this error when i select an entity guys. It was working before.

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/ce5bd40501c3d69081d6f1fd88a631198945b083

**Comment by stickyhands** [comment] 2015-03-03 09:18
is it fixed now?

**Comment by sergiostrampelli** [comment] 2015-03-11 10:04
+1

**Comment by sergiostrampelli** [comment] 2015-03-11 11:56
https://github.com/sonata-project/SonataAdminBundle/commit/fe56a06778a424730bc0d0781e68f29ccbb49c69

**Comment by stickyhands** [comment] 2015-03-12 14:29
@sujayjaju based on your idea, I created app/Resources/SonataAdminBundle/views/CRUD/list__select.html.twig containing that change:
https://github.com/sonata-project/SonataAdminBundle/commit/fe56a06778a424730bc0d0781e68f29ccbb49c69

works great

**Comment by jordisala1991** [comment] 2018-03-12 20:10
Seems like the issue is solved. Closing

If it is not, please ping me to reopen.

**Closed by jordisala1991** 2018-03-12 20:10 UTC
