### ISSUE TITLE
ChoiceType option choice_translation_domain doesn't work in combination with expanded option for doctrine_orm_choice in DatagridMapper

### ISSUE THREAD

**Issue by verheyenkoen** [sonata-project/SonataDoctrineORMAdminBundle#620] opened 2016-09-02 10:16 UTC
#### Sonata packages

``` bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.5.0  The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.1.0  Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.0.5  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
```
#### Symfony packages

``` bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.9  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.9  The Symfony PHP framework
symfony/var-dumper         v3.1.3  Symfony mechanism for exploring and dumping PHP variables
```
#### PHP version

``` bash
$ php -v
PHP 5.5.37 (cli) (built: Jun 24 2016 20:55:10) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with blackfire v1.10.6-refs/heads/prod+1369-internal, https://blackfire.io, by Blackfireio Inc.
```
## Subject

When adding a `doctrine_orm_choice` field in `configureDatagridFilters()`, the option `choice_translation_domain` seems to be ignored when used in combination with `'expanded' => true`, making it impossible to change the translation domain for choice option labels or disabling translation. This appears to have been a Symfony bug but it is already fixed (since 2.7): https://github.com/symfony/symfony/issues/15140. No idea why this doesn't work automatically in Sonata Admin.
## Steps to reproduce

``` php
$datagridMapper
  ->add('status', 'doctrine_orm_choice', array(), ChoiceType::class, array(
    'choices' = [...],
    'expanded' => true,
    'choice_translation_domain' => false,
  ))
```
## Expected results

The labels used in `choices` should not be translated in this occasion (which is what happens if you omit `'expanded' => true`).
## Actual results

Symfony profiler shows warnings about missing translations for these options.

**Comment by jordisala1991** [comment] 2018-04-01 09:45
This one seems like a duplicate of this other one: https://github.com/sonata-project/SonataAdminBundle/issues/4550

This will create a relation between the two issues, but Im also closing it for now. If you think those issues are different, please ping me to reopen.

**Closed by jordisala1991** 2018-04-01 09:45 UTC
