### ISSUE TITLE
ChoiceFilter should handle NULL value (and have a better support of ALL value).

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataDoctrineORMAdminBundle#991] opened 2020-02-22 14:27 UTC
## Feature Request

This is the `ChoiceFilter` code
```php
if (\is_array($data['value'])) {
    if (0 === \count($data['value'])) {
        return;
    }

    if (\in_array('all', $data['value'], true)) {
        return;
    }

    // Have to pass IN array value as parameter. See: http://www.doctrine-project.org/jira/browse/DDC-3759
    $completeField = sprintf('%s.%s', $alias, $field);
    $parameterName = $this->getNewParameterName($queryBuilder);
    if (ChoiceType::TYPE_NOT_CONTAINS === $data['type']) {
        $this->applyWhere($queryBuilder, $queryBuilder->expr()->notIn($completeField, ':'.$parameterName));
    } else {
        $this->applyWhere($queryBuilder, $queryBuilder->expr()->in($completeField, ':'.$parameterName));
    }
    $queryBuilder->setParameter($parameterName, $data['value']);
} else {
    if ('' === $data['value'] || null === $data['value'] || false === $data['value'] || 'all' === $data['value']) {
        return;
    }

    $parameterName = $this->getNewParameterName($queryBuilder);

    if (ChoiceType::TYPE_NOT_CONTAINS === $data['type']) {
        $this->applyWhere($queryBuilder, sprintf('%s.%s <> :%s', $alias, $field, $parameterName));
    } else {
        $this->applyWhere($queryBuilder, sprintf('%s.%s = :%s', $alias, $field, $parameterName));
    }

    $queryBuilder->setParameter($parameterName, $data['value']);
}
```

You can see that:
- There is a specific behaviour for the `all` value. AFIK, this is not documented. And if you chose the `all` value, the filter is not applied, even if you chose the `NOT CONTAINS` operator. But, for me it should return no results instead of every result. IMHO, the `all` behaviour should be deprecated or at least fixed.
- I have multiple filter where sometimes I want to get all entities with the value A, sometimes all entities with the value B, and sometimes all entities with no value in database since my field is nullable. Actually the choice filter does not handle null values. 

So if `$data['value'] = null`, I expect the query to do `IS NULL` or `IS NOT NULL`.
And if `$data[`value`]` is an array with a null value, I expect to add a `OR IS NULL` check.

I can make the PR if you agree with the changes.

**Comment by VincentLanglet** [comment] 2020-02-27 10:46
@greg0ire @OskarStark @core23 @phansys 
We're considering taking time next time in our company to implement this feature on Sonata. Do you agree with these changes/improvement ?
Do you consider this as BC or BC-break ?

**Comment by OskarStark** [comment] 2020-02-27 12:39
Your explanation sounds valid to me, and I am missing this kind of filter too 👍

**Comment by greg0ire** [comment] 2020-02-27 19:13
If it's not documented then it's not a BC-break :P I agree with the change, and let's document and test the new behavior :)

**Comment by phansys** [comment] 2020-02-28 00:15
It would be a great improvement.

**Comment by greg0ire** [comment] 2020-02-28 21:17
Also @VincentLanglet , I tried to contact you on the Symfony devs Slack to ask you to join the team :)

**Comment by VincentLanglet** [comment] 2020-02-28 21:41
Oh ! I'm never log in on the symfony-dev slack. I should try to be more often.
I'll be happy to join the team. @greg0ire

**Comment by greg0ire** [comment] 2020-02-28 22:17
Great! Please send me your email address in that Slack so that we can invite you to the Sonata Slack :)

**Comment by VincentLanglet** [comment] 2020-03-01 01:44
The PR for this issue will close https://github.com/sonata-project/SonataAdminBundle/issues/3569 too

**Comment by OskarStark** [comment] 2020-03-02 11:12
cc @peter-gribanov

**Comment by peter-gribanov** [comment] 2020-03-02 12:02
> Actually the choice filter does not handle null values.

The problem i described is related to this part. Sometimes it is necessary to find all entities whose field value is empty or null.

You can't just remove [this condition](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/src/Filter/ChoiceFilter.php#L48-L50), because in this case absolutely all filters will be applied. Perhaps we should rely on the type of filter. If the user explicitly changes the type of filter, then he understands what he is doing. That is, we can ignore requests in which the filter type is not selected.

```php
if (!$data['type'] || $data['type'] === ChoiceType::TYPE_CONTAINS /* default filter type */) {
    if ('' === $data['value'] || null === $data['value'] || false === $data['value'] || 'all' === $data['value']) {
        return;
    }
}
```

So, users can use `ChoiceType::TYPE_NOT_CONTAINS` and `ChoiceType::TYPE_EQUAL` [filter types](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Form/Type/Filter/ChoiceType.php) to search by empty value.

To search for null values, you can add `ChoiceType::TYPE_IS_NULL` and `ChoiceType::TYPE_IS_NOT_NULL` filter types. 

It doesn't seem native to me and therefore i didn’t offer it last time. Maybe someone has better ideas?

**Comment by VincentLanglet** [comment] 2020-03-06 13:49
> > Actually the choice filter does not handle null values.
> 
> The problem i described is related to this part. Sometimes it is necessary to find all entities whose field value is empty or null.
> 
> You can't just remove [this condition](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/src/Filter/ChoiceFilter.php#L48-L50), because in this case absolutely all filters will be applied.

I just want to remove the check for the `null` value.

![image](https://user-images.githubusercontent.com/9052536/76088900-1a1e4000-5fb9-11ea-956f-b8aadefcc7c2.png)

In this scenario
- The first filter is not apply, filter function is not even called.
- The second filter is apply
- The last filter called filter with a `$data['value']` null. ATM it does nothing, but if I remove the check for `null === $data['value']`. It's applied.

The PR should be coming today.

BTW, WDYT about removing the special scenario for `all` value ?

> If it's not documented then it's not a BC-break :P I agree with the change, and let's document and test the new behavior :)

Do you mean I can remove the `all` value case in a minor because it's not documented ? @greg0ire

**Comment by rgrassian** [comment] 2020-03-06 16:12
I just created PR #999

**Comment by peter-gribanov** [comment] 2020-03-06 16:21
@VincentLanglet this is about nullable values, but what about empty values sonata-project/SonataAdminBundle#3569 ?

**Comment by VincentLanglet** [comment] 2020-03-06 16:38
> @VincentLanglet this is about nullable values, but what about empty values [sonata-project/SonataAdminBundle#3569](https://github.com/sonata-project/SonataAdminBundle/issues/3569) ?

This may be another feature, we were mainly talking about nullable value in this issue.
There was a difference between a filter without value and filter with a `null` value.

But I don't really understand what you mean by `empty value` ?

If you're talking about `''` value, so I recommend to do https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/943

**Comment by peter-gribanov** [comment] 2020-03-06 16:50
> If you're talking about '' value, so I recommend to do #943

Including about it. So this is a duplicate of my issue.

**Comment by VincentLanglet** [comment] 2020-03-06 16:51
> > If you're talking about '' value, so I recommend to do #943
> 
> Including about it. So this is a duplicate of my issue.

But this is not related to this issue.

**Comment by peter-gribanov** [comment] 2020-03-06 16:58
> But this is not related to this issue.

You yourself mentioned the connection https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/991#issuecomment-593028877

There issues is a related, because in my issue i am talking about finding records with an empty value. This is both an empty string `''` #943 and `null` #991.

**Comment by VincentLanglet** [comment] 2020-03-06 17:11
> > But this is not related to this issue.
> 
> You yourself mentioned the connection [#991 (comment)](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/991#issuecomment-593028877)
> 
> There issues is a related, because in my issue i am talking about finding records with an empty value. This is both an empty string `''` #943 and `null` #991.

There is ton of empty value depending on the situation `''`, `false`, `0`, `'0'`, `null`, `[]`, ...
So please, stop talking about empty value. Talk about the value you're looking for, and split them in separate choices/filter.

If I look for all the `null` value, the filter you're asking won't help me. For me `''` is not a `null` value. If someone look for `''` values, he clearly not want the `'0'` value, so again your filter won't help.

**Comment by peter-gribanov** [comment] 2020-03-06 20:20
> So please, stop talking about empty value. Talk about the value you're looking for, and split them in separate choices/filter.

I repeat.  I set a common task.  You are considering a special case.  That is, your task turns out to be a subtask in relation to mine.

**Comment by greg0ire** [comment] 2020-03-06 20:22
> Do you mean I can remove the all value case in a minor because it's not documented ? @greg0ire

And because you think it is broken. Not being documented is not enough alone IMO

**Closed** 2020-03-16 16:44 UTC
Labels: feature
