### ISSUE TITLE
Getting the parent admin class uniqid in edit_orm_* templates

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataDoctrineORMAdminBundle#378] opened 2014-09-03 13:40 UTC
In my parent admin class I have a `integratorBranch' element and the generated html looks like this:

``` html
<select class="select2-offscreen" required="required" name="s5407142702fb0[integratorBranch]" id="s5407142702fb0_integratorBranch" tabindex="-1" title=""><option value="2">Emden</option></select>
```

The `uniqid` generated for parent admin class in this example is `s5407142702fb0`.

In this parent form I have a ManyToOne relation `integratorContacts`. Inside the Javascript of this relation I need an extra value - the value of the selected `integratorBranch` above.

I can successfully override the `edit_orm_many_association_script.html` script and the desired `field_dialog_form_add_{{ id }}(link)` function:

``` twig
        var integratorBranch = jQuery('#{{ sonata_admin.admin.uniqid }}_integratorBranch');
        console.log('{{ sonata_admin.admin.uniqid }}');
        console.log('{{ id }}');
```

Unfortunately the `sonata_admin.admin.uniqid` does not equal the original uniqid `s5407142702fb0`.
But the `id` actually includes the correct uniqid + the name of my collection:
`s5407142702fb0_integratorContacts_0_user`.

Of course I could to some string workaround:

``` javascript
var integratorBranch = jQuery('select[id$=_integratorBranch]');       
```

I also tried setting a fixed ID on the element but the `uniqid` is added to the fixed ID:

``` php
            ->add('integratorBranch', 'sonata_type_model', array(
                'label' => false,
                'widget_add_btn' => false,
                'attr' => array(
//                    'id' => 'integratorBranch' // creates uniqid + id e.g. s5407142702fb0_integratorBranch
                )
            ))
```

But I think there is a way to "easily" get the parent admin class `uniqid` e.g.:

Another question: Is there a better practice to override a single javascript function?
The console log mentions the event this way:

``` javascript
[Sonata.Admin] [s5407142702fb0_integratorContacts_0_user|field_dialog_form_add] add link action
```

This is the complete function I would like to customize:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/views/CRUD/edit_orm_many_association_script.html.twig#L139-176

**Comment by core23** [comment] 2016-08-27 12:43
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by kunicmarko20** [comment] 2018-04-01 01:29
As there was no reply recently, I will close it. Ping me if reopen is needed.

**Closed by kunicmarko20** 2018-04-01 01:29 UTC
Labels: pending author
